#1. Fundamentals of Programming

In [1]:
print(type(5))
print(type('hello'))
print(type([]))
print(type(str)) #int, str, and list are all instances of the class type

<class 'int'>
<class 'str'>
<class 'list'>
<class 'type'>


In [ ]:
x = 1
x = x + 2
print(x)

x = 1
x += 2
print(x)

a = "Deep"
b = 'Learning'
print(a + b)
print(a + " " + b)

3
3
DeepLearning
Deep Learning


In [ ]:
print(not(False and not False or not (not False or False)))
print(not(False and True or not (True or False)))
print(not(False and True or not True))
print(not(False and True or False))
print(not(False or False))
print(not(False))

True
True
True
True
True
True


## Quiz

### Q1
What is the output of `print(a)`?

In [3]:
a = type(type(4))

###Solution

In [6]:
a

type

### Q2
What is the output of `print(x)`?

In [ ]:
x = 4
x *= 2
x -= 4

### Solution

In [ ]:
x

4

###Q3
What is the output of `print(a)`?

In [ ]:
a = not(True and (not False or False))
#not(True and (True or False))
#not(True and True)
#not(True)
#False

### Solution

In [ ]:
a

False

##Exercise 1
Calculate the value of $5 ∗ \big(2 + 4^3\big)$ using Python


In [ ]:
5 * (2 + 4 ** 3)

330

##Exercise 2
In `R`, you can use the function `is.string()` to determine whether a value is a string. Unfortunately, there isn’t a similar function in Python. Can you figure out a way to check whether a value is a string in Python? What about an integer or a bool?

In [ ]:
x = "hello"
print(x == str(x))

True


In [ ]:
# Check if a value is a string
value = "hello"
print(isinstance(value, str))  

# Check if a value is an integer
value = 123
print(isinstance(value, int))  

# Check if a value is a boolean
value = True
print(isinstance(value, bool)) 

True
True
True


##Exercise 3
What is the value of `type(type(bool(int("3"))))`?

In [ ]:
type(type(bool(int("3"))))

type

In [ ]:
print(int("3"))
print(bool(int("3"))) #bool(integer) is True
print(type(bool(int("3")))) #the class of True or False is bool
print(type(type(bool(int("3"))))) #the class of bool is type

3
True
<class 'bool'>
<class 'type'>


##Exercise 4
What is the value of `not(True and not False or False and not (True or False))`?

In [ ]:
not(True and not False or False and not (True or False))

False

#2. Data Structures and Accessing

In [8]:
import numpy as np
#list
lst1 = [1, 2, 3, 4]
lst2 = [5, 6, 7, 8]

#convert lists to arrays
a1 = np.array(lst1)
a2 = np.array(lst2)

print(lst1+lst2) #adding lists
print(a1+a2) #adding arrays
print(lst1*2) #scaling a list
print(a1*2) #scaling an array


[1, 2, 3, 4, 5, 6, 7, 8]
[ 6  8 10 12]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [ ]:
a1 = np.array([1, 2])
a2 = np.array([3, 4])

#Concatenating arrays
print(np.concatenate((a1, a2), axis = 0))

[1 2 3 4]


In [12]:
#list comprehension
lst = [1, 2, 3, 4]
print([i**2 for i in lst])



[1, 4, 9, 16]


In [ ]:
#Changing a list
lst1 = [1, 2, 3, 4]

#add 5 at the end
lst1.append(5)
print(lst1)

#add 0 at the end
lst1.append(0)
print(lst1)

#sort the list from smallest to the largest
lst1.sort()
print(lst1)

#remove 2 from the list
lst1.remove(2)
print(lst1)

#insert -1 at index 0 
lst1.insert(0, -1)
print(lst1)

#reverse the list
lst1.reverse()
print(lst1)

#pop the last object
lst1.pop()
print(lst1)

#remove 0 from the list
lst1.remove(0)
print(lst1)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 0]
[0, 1, 2, 3, 4, 5]
[0, 1, 3, 4, 5]
[-1, 0, 1, 3, 4, 5]
[5, 4, 3, 1, 0, -1]
[5, 4, 3, 1, 0]
[5, 4, 3, 1]


In [ ]:
#Dictionary
wam_dict = {"Alice": 87.4, "Bob": 77.9, "Charlie": 81.3}
print(wam_dict.keys())
print(wam_dict.values())

#Add "Eric": 5 to this dictionary
wam_dict["Eric"] = 50.0
print(wam_dict)

dict_keys(['Alice', 'Bob', 'Charlie'])
dict_values([87.4, 77.9, 81.3])
{'Alice': 87.4, 'Bob': 77.9, 'Charlie': 81.3, 'Eric': 50.0}


##Quiz

###Q1
What are the outputs of `print(a1)` and `print(a2)`?

In [ ]:
lst1 = [1, 2]
lst2 = [2, 1]
a1 = (lst1 + lst2) * 2 #Cannot perform arithmetic operations on a list
a2 = (np.array(lst1) + np.array(lst2)) * 2

###Solution

In [ ]:
print(a1)
print(a2)

[1, 2, 2, 1, 1, 2, 2, 1]
[6 6]


###Q2
What is the output of `print(A)`?

In [ ]:
lst = [1, 2, 3, 4]
A = [i for i in lst if i % 2 == 0] #We are only taking in the value i if i is divisible by 2

###Solution

In [ ]:
print(A)

[2, 4]


###Q3
What is the output of `print(lst1)`?

In [ ]:
lst1 = [1, 2, 3]
lst1.pop() #[1, 2]
lst1.reverse() #[2, 1]
lst1.append(3) #[2, 1, 3]

###Solution

In [ ]:
print(lst1)

[2, 1, 3]


##Exercise 1
This exercise will get you familiar with Python’s built-in list methods.
1. Create an empty list and assign it to the variable l.
2. Append the numbers 7, 2, and 11 to the list.
3. Sort the list using the `sort()` method.
4. Insert the number 8 at index 1 using the `insert()` method.
5. Reverse the list using `reverse()`.
6. Call `pop()` on the list twice.
7. Use `remove()` to remove the number 11 from the list.
8. Print the list.
9. Clear the list.

In [ ]:
# 1. Create an empty list and assign it to the variable l.
l = []

# 2. Append the numbers 7, 2, and 11 to the list.
l.append(7) 
#[7]
l.append(2)
#[7, 2]
l.append(11)
#[7, 2, 11]

# 3. Sort the list using the sort() method.
l.sort()
#[2, 7, 11]

# 4. Insert the number 8 at index 1 using the insert() method.
l.insert(1, 8)
#[2, 8, 7, 11]

# 5. Reverse the list using reverse().
l.reverse()
#[11, 7, 8, 2]

# 6. Call pop() on the list twice.
l.pop()
#[11, 7, 8]
l.pop()
#[11, 7]

# 7. Use remove() to remove the number 11 from the list.
l.remove(11)
#[7]

# 8. Print the list.
print(l)

# 9. Clear the list.
l.clear()
#[]

[7]


##Exercise 2
This exercise will teach you how to build a dictionary by combining a list and a tuple. This can also be done with two lists or two tuples.
1. Create a tuple containing the values “Circle”, “Triangle”, and “Square”. Call this tuple shapes.
2. Create a list containing the values 1, 3, and 4. Call this list sides.
3. Combine shapes and sides using `dict(zip())`. Print the dictionary.
4. Add "Pentagon": 5 to this dictionary to show that it is mutable. Print the dictionary.

In [ ]:
# 1. Create a tuple containing the values "Circle", "Triangle", and "Square". Call this tuple shapes.
shapes = ("Circle", "Triangle", "Square")

# 2. Create a list containing the values 1, 3, and 4. Call this list sides.
sides = [1, 3, 4]

# 3. Combine shapes and sides using dict(zip()). Print the dictionary.
shape_sides_dict = dict(zip(shapes, sides))
print(shape_sides_dict) 

# 4. Add "Pentagon": 5 to this dictionary 
shape_sides_dict["Pentagon"] = 5
print(shape_sides_dict)

{'Circle': 1, 'Triangle': 3, 'Square': 4}
{'Circle': 1, 'Triangle': 3, 'Square': 4, 'Pentagon': 5}


#3. Loops

In [ ]:
import numpy as np
#Construct a 4*2 matrix 
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(A)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Matrix multiplication A^T B 
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
B = np.array([1, -1]).reshape(-1) #reshape forces a column vector 
print(A.T @ B)
print(B.reshape(1,2)) #reshape B into a row vector

[-4 -4 -4 -4]
[[ 1 -1]]


In [ ]:
#If loop
a = 5
b = 4
c = 3

sum = 0
#Check if a is greater than b
if a > b:
    sum += a
    #Check if b is greater than c
    if b > c:
        sum += b
    else:
        sum += c
print(sum)

9


In [ ]:
#For loop
fruits = ['apple', 'orange', 'watermelon']
#iterate over all the objects in the fruits list
for fruit in fruits:
    print(fruit)

apple
orange
watermelon


In [ ]:
#While loop
fruits = ['apple', 'orange', 'watermelon']
i = 0
#check if the length of the string is less than or equal to 6
while len(fruits[i]) <= 6:
    print(fruits[i])
    i += 1

apple
orange


##Quiz

###Q1
What is the shape of the following matrix `A`?

In [16]:
A = np.array([[1., 1.], [0., 0.], [2., 2.]])

###Solution

In [18]:
print(A.shape)

(3, 2)


###Q2
What is the final output of `print(weights)`?

In [ ]:
weights = np.array([2., 2.])
num_iterations = 2
gradients = np.array([[1., 1.], [2., 2.]])

for _ in range(num_iterations):
  weights -= 0.5 * gradients[_]


###Solution

In [ ]:
print(weights)

[0.5 0.5]


##Exercise 1
Recreate the FizzBuzz program - a classic task in coding interviews - in Python. FizzBuzz is a children’s game in which people in a circle count to 100 - with a twist. Your FizzBuzz program should loop from 1 to 50, and print, on a new line:

- “Fizz!” if the current number is divisible by 3
- “Buzz!” if the current number is divisible by 5
- “FizzBuzz!” if the current number is divisible by both 3 and 5 • Otherwise, print the current number.

In [ ]:
# Loop from 1 to 50
for i in range(1, 51):
    # Check if the number is divisible by both 3 and 5
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz!")
    # Check if the number is divisible by 3
    elif i % 3 == 0:
        print("Fizz!")
    # Check if the number is divisible by 5
    elif i % 5 == 0:
        print("Buzz!")
    # If the number is not divisible by either 3 or 5, print the number
    else:
        print(i)

1
2
Fizz!
4
Buzz!
Fizz!
7
8
Fizz!
Buzz!
11
Fizz!
13
14
FizzBuzz!
16
17
Fizz!
19
Buzz!
Fizz!
22
23
Fizz!
Buzz!
26
Fizz!
28
29
FizzBuzz!
31
32
Fizz!
34
Buzz!
Fizz!
37
38
Fizz!
Buzz!
41
Fizz!
43
44
FizzBuzz!
46
47
Fizz!
49
Buzz!


##Exercise 2
This exercise will introduce you to the break and continue statements in Python.
- Create a new list with the numbers 3, 7, -9, 11, 2, -5, 0, 4.
- Create a variable, sum_pos, and set it equal to 0.
- Create a for loop that iterates through each of the numbers in the list. 
- If the current number is positive, add it to sum_pos.
- If the current number is negative, ignore it and move to the next number using the continue statement.
- If the current number is zero, stop the loop using break.


In [ ]:
# Create a new list with the numbers 3, 7, -9, 11, 2, -5, 0, 4.
lst = [3, 7, -9, 11, 2, -5, 0, 4]

# Create a variable, sum_pos, and set it equal to 0.
sum_pos = 0

# Create a for loop that iterates through each of the numbers in the list.
for num in lst:
    # If the current number is positive, add it to sum_pos.
    if num > 0:
        sum_pos += num
    # If the current number is negative, ignore it and move to the next number using the continue statement.
    elif num < 0:
        continue
    # If the current number is zero, stop the loop using break.
    elif num == 0:
        break

print(sum_pos)  

23


#Functions

##Quiz

###Q1
What is the output of 
- `print(madness(3))`
- `print(madness(6))`
- `print(madness(9))`
- `print(madness(12))`
- `print(madness(14))`

In [19]:
def madness(k):
  if k < 5:
    return(k**2)
  elif k >= 5 and k < 10:
    if k < 8:
      return(k)
    else:
      return(0)
  else:
    return(madness(k-5))

###Solution

In [20]:
print(madness(3))
print(madness(6))
print(madness(9))
print(madness(12))
print(madness(14))

9
6
0
7
0


##Exercise 1
Build a function, `factorial(n)`, that takes in one input `n`, and returns `n!`.

In [ ]:
def factorial(n):
    # Base case: factorial of 0 is 1
    if n == 0:
        return 1
    # Recursive case: n! = n * (n-1)!
    else:
        return n * factorial(n-1)

##Exercise 2
Build a function, `fibonacci(n)`, that takes in one input `n`, and returns the `n`th Fibonacci number.

In [ ]:
def fibonacci(n):
    # The first Fibonacci number is 0
    if n == 0:
        return 0
    # The second Fibonacci number is 1
    elif n == 1:
        return 1
    # For all other n, the nth Fibonacci number is (n-1)th plus (n-2)th Fibonacci number
    else:
        return fibonacci(n-1) + fibonacci(n-2)

#5. Data Processing

In [21]:
import pandas as pd
import numpy as np
titanic = pd.read_csv("train.csv")
titanic.head()

FileNotFoundError: ignored

In [ ]:
#proportion of survivals
passengers_status = titanic['Survived']
print(f'The proportion of survivals is {round(np.sum(passengers_status)/len(passengers_status), 4)}')

#proportion of adolescent
adolescent_bool = titanic["Age"] < 18
adolescent_indicators =  adolescent_bool * 1
print(f'The proportion of adolescent is {round(np.sum(adolescent_indicators)/len(adolescent_indicators), 4)}')

#proportion of adolescent survivors
adolescent_status = titanic[adolescent_bool]['Survived']
print(f'The proportion of adolescent survivors is {round(np.sum(adolescent_status)/len(adolescent_status), 4)}')

#proportion of adult survivors
adult_status = titanic[[not state for state in adolescent_bool]]['Survived']
print(f'The proportion of adult survivors is {round(np.sum(adult_status)/len(adult_status), 4)}')

The proportion of survivals is 0.3838
The proportion of adolescent is 0.1268
The proportion of adolescent survivors is 0.5398
The proportion of adult survivors is 0.3612


##Exercise 1
Filter the dataset to people where Embarked is Q.

In [ ]:
titanic[titanic["Embarked"] == "Q"]

PassengerId  Survived  Pclass                                  Name  \
5              6         0       3                      Moran, Mr. James   
16            17         0       3                  Rice, Master. Eugene   
22            23         1       3           McGowan, Miss. Anna "Annie"   
28            29         1       3         O'Dwyer, Miss. Ellen "Nellie"   
32            33         1       3              Glynn, Miss. Mary Agatha   
..           ...       ...     ...                                   ...   
790          791         0       3              Keane, Mr. Andrew "Andy"   
825          826         0       3                       Flynn, Mr. John   
828          829         1       3          McCormack, Mr. Thomas Joseph   
885          886         0       3  Rice, Mrs. William (Margaret Norton)   
890          891         0       3                   Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
5      male   NaN      0      0  330877   8.4583   NaN        Q  
16     male   2.0      4      1  382652  29.1250   NaN        Q  
22   female  15.0      0      0  330923   8.0292   NaN        Q  
28   female   NaN      0      0  330959   7.8792   NaN        Q  
32   female   NaN      0      0  335677   7.7500   NaN        Q  
..      ...   ...    ...    ...     ...      ...   ...      ...  
790    male   NaN      0      0   12460   7.7500   NaN        Q  
825    male   NaN      0      0  368323   6.9500   NaN        Q  
828    male   NaN      0      0  367228   7.7500   NaN        Q  
885  female  39.0      0      5  382652  29.1250   NaN        Q  
890    male  32.0      0      0  370376   7.7500   NaN        Q  

[77 rows x 12 columns]

In [ ]:
latex_table = titanic[titanic["Embarked"] == "Q"].to_latex(index=False)
print(latex_table)

\begin{tabular}{rrrllrrrlrll}
\toprule
 PassengerId &  Survived &  Pclass &                                            Name &    Sex &  Age &  SibSp &  Parch &     Ticket &    Fare & Cabin & Embarked \\
\midrule
           6 &         0 &       3 &                                Moran, Mr. James &   male &  NaN &      0 &      0 &     330877 &  8.4583 &   NaN &        Q \\
          17 &         0 &       3 &                            Rice, Master. Eugene &   male &  2.0 &      4 &      1 &     382652 & 29.1250 &   NaN &        Q \\
          23 &         1 &       3 &                     McGowan, Miss. Anna "Annie" & female & 15.0 &      0 &      0 &     330923 &  8.0292 &   NaN &        Q \\
          29 &         1 &       3 &                   O'Dwyer, Miss. Ellen "Nellie" & female &  NaN &      0 &      0 &     330959 &  7.8792 &   NaN &        Q \\
          33 &         1 &       3 &                        Glynn, Miss. Mary Agatha & female &  NaN &      0 &      0 &     335677 

<ipython-input-47-4eb696607c5e>:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  latex_table = titanic[titanic["Embarked"] == "Q"].to_latex(index=False)


In [ ]:
#Number of survivors boarded from Queestown
Q_people = titanic[titanic["Embarked"] == "Q"]
Q_status = Q_people['Survived']
print(np.sum(Q_status))
#Using groupby
titanic.groupby("Embarked").sum()["Survived"]

30


<ipython-input-48-125191af49cd>:6: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  titanic.groupby("Embarked").sum()["Survived"]


Embarked
C     93
Q     30
S    217
Name: Survived, dtype: int64

##Exercise 2
Filter the dataset to people 18 years or older, and Fare is less than 10

In [ ]:
titanic.query("Age >= 18 & Fare < 10")

PassengerId  Survived  Pclass                            Name     Sex  \
0              1         0       3         Braund, Mr. Owen Harris    male   
2              3         1       3          Heikkinen, Miss. Laina  female   
4              5         0       3        Allen, Mr. William Henry    male   
12            13         0       3  Saundercock, Mr. William Henry    male   
37            38         0       3        Cann, Mr. Ernest Charles    male   
..           ...       ...     ...                             ...     ...   
876          877         0       3   Gustafsson, Mr. Alfred Ossian    male   
877          878         0       3            Petroff, Mr. Nedelio    male   
881          882         0       3              Markun, Mr. Johann    male   
884          885         0       3          Sutehall, Mr. Henry Jr    male   
890          891         0       3             Dooley, Mr. Patrick    male   

      Age  SibSp  Parch            Ticket    Fare Cabin Embarked  
0    22.0      1      0         A/5 21171  7.2500   NaN        S  
2    26.0      0      0  STON/O2. 3101282  7.9250   NaN        S  
4    35.0      0      0            373450  8.0500   NaN        S  
12   20.0      0      0         A/5. 2151  8.0500   NaN        S  
37   21.0      0      0        A./5. 2152  8.0500   NaN        S  
..    ...    ...    ...               ...     ...   ...      ...  
876  20.0      0      0              7534  9.8458   NaN        S  
877  19.0      0      0            349212  7.8958   NaN        S  
881  33.0      0      0            349257  7.8958   NaN        S  
884  25.0      0      0   SOTON/OQ 392076  7.0500   NaN        S  
890  32.0      0      0            370376  7.7500   NaN        Q  

[216 rows x 12 columns]

##Exercise 3
Filter the dataset to people with an above-median age.

In [ ]:
#Drop rows (observations) with "Age" missing
filtered_age_df = titanic.dropna(subset=["Age"])
#Find people with an above-median age.
filtered_age_df[filtered_age_df["Age"] >= np.median(filtered_age_df["Age"])]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
6              7         0       1   
11            12         1       1   
..           ...       ...     ...   
879          880         1       1   
881          882         0       3   
883          884         0       2   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
883                      Banfield, Mr. Frederick James    male  28.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
6        0             17463  51.8625   E46        S  
11       0            113783  26.5500  C103        S  
..     ...               ...      ...   ...      ...  
879      1             11767  83.1583   C50        C  
881      0            349257   7.8958   NaN        S  
883      0  C.A./SOTON 34068  10.5000   NaN        S  
885      5            382652  29.1250   NaN        Q  
890      0            370376   7.7500   NaN        Q  

[377 rows x 12 columns]

##Exercise 4
What is the highest value of Fare for female passengers in class 2?

In [ ]:
#Obtain a dataset of female passengers in class 2
class2_female = titanic.query("Sex == 'female' & Pclass == 2")
#find the highest value of fare 
np.max(class2_female['Fare'])

65.0